mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    expose:
    - '3306'
    volumes:
    - ./data/mysql:/var/lib/mysql

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links: 
        - mysql:db
    ports:
        - 8081:80
    environment:
        PMA_HOST: 'mysql'
        PMA_USER: 'root'
        PMA_PASSWORD: 'password'