test:
    build: ./source/scripts
    container_name: test
    restart: always
    links: 
        - mysql:db
    ports:
        - 8080:80
    volumes:
        - ./source/scripts:/var/www/html

mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    expose:
    - '3306'
    volumes:
    - ./data/mysql:/var/lib/mysql

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links: 
        - mysql:db
    ports:
        - 8081:80
    environment:
        PMA_HOST: 'mysql'
        PMA_USER: 'root'
        PMA_PASSWORD: 'password'



master:
    image: 'christianbladescb/locustio'
    container_name: 'master'
    restart: always
    command: " -f locustfile.py --host=test:80 --master
    "
    ports:
    - "8089:8089"
    - "5557:5557"
    volumes:
    - ./source/locust/benchmarks:/locust

slave:
    image: 'christianbladescb/locustio'
    container_name: 'slave'
    restart: 'always'
    command: " -f locustfile.py --host=test:80 --slave --master-host=master"
    volumes:
    - ./source/locust/benchmarks:/locust